apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: my-namespace
spec:
  automountServiceAccountToken: false
  containers:
  - name: bad-pod
    image: alpine@sha256:3d426b0bfc36
    imagePullPolicy: Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"
      requests:
        memory: "64Mi"
        cpu: "0.5"
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
    securityContext:
      privileged: true
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 20000
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 3