name: Prisma Cloud
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Prisma Cloud 
        id: Prisma
        uses: bridgecrewio/bridgecrew-action@master 
        env:
          PRISMA_API_URL: https://api3.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
